"""initial schema

Revision ID: 1f36c077b258
Revises: 
Create Date: 2026-04-02 13:40:05.589661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f36c077b258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nombre_curso', sa.Text(), nullable=False),
    sa.Column('descripcion_curso', sa.Text(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gratuito', sa.Boolean(), nullable=True),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inscripciones',
    sa.Column('id_inscripcion', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('progreso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_ultima_actividad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_inscripcion'),
    sa.UniqueConstraint('usuario_id', 'curso_id')
    )
    op.create_table('logros_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('puntos_otorgados', sa.Integer(), nullable=True),
    sa.Column('fecha_obtenido', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tipo', 'titulo')
    )
    op.create_table('niveles_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=True),
    sa.Column('puntos_totales', sa.Integer(), nullable=True),
    sa.Column('racha_dias', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_actividad', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('perfiles_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=100), nullable=True),
    sa.Column('universidad', sa.String(length=200), nullable=True),
    sa.Column('carrera', sa.String(length=200), nullable=True),
    sa.Column('tipo_suscripcion', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio_suscripcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin_suscripcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objetivo_estudio', sa.Text(), nullable=True),
    sa.Column('tiempo_estudio_diario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('leccion', sa.Integer(), nullable=False),
    sa.Column('planteamiento', sa.Text(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('opciones', sa.JSON(), nullable=False),
    sa.Column('respuesta_correcta', sa.Text(), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('progreso_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('lecciones_completadas', sa.Integer(), nullable=True),
    sa.Column('preguntas_respondidas', sa.Integer(), nullable=True),
    sa.Column('preguntas_correctas', sa.Integer(), nullable=True),
    sa.Column('tiempo_total_estudio', sa.Integer(), nullable=True),
    sa.Column('porcentaje_completado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ultima_actividad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'curso_id')
    )
    op.create_table('retos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('objetivo', sa.Integer(), nullable=False),
    sa.Column('progreso_actual', sa.Integer(), nullable=True),
    sa.Column('puntos_recompensa', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones_estudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('leccion', sa.Integer(), nullable=True),
    sa.Column('tipo_actividad', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ultima_actividad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracion_total', sa.Integer(), nullable=True),
    sa.Column('tiempo_activo', sa.Integer(), nullable=True),
    sa.Column('preguntas_respondidas', sa.Integer(), nullable=True),
    sa.Column('paginas_vistas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_usuario',
    sa.Column('id_respuesta', sa.Integer(), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('respuesta_usuario', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.Column('tiempo_respuesta', sa.Integer(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_pregunta'], ['preguntas.id_pregunta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta'),
    sa.UniqueConstraint('id_pregunta', 'id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_usuario')
    op.drop_table('sesiones_estudio')
    op.drop_table('retos_usuario')
    op.drop_table('progreso_usuario')
    op.drop_table('preguntas')
    op.drop_table('perfiles_usuario')
    op.drop_table('niveles_usuario')
    op.drop_table('logros_usuario')
    op.drop_table('inscripciones')
    op.drop_table('usuarios')
    op.drop_table('cursos')
    # ### end Alembic commands ###
